Repository 100Devs-ADHD/think-big, pull requests merged in 2022-08, with the labels that each got.

#101 feat(ui): ✨ create ClassStatusSwitch component
  .husky/post-checkout
  .husky/post-rewrite
  package.json
  prisma/schema.prisma
  src/common/dbSelect/assignment.ts
  src/common/dbSelect/index.ts
  src/common/dbSelect/user.ts
  src/components/ClassTable/ClassAccordianTable.tsx
  src/components/ClassTable/ClassDetail.tsx
  src/components/ClassTable/ClassRow.tsx
  src/components/ClassTable/ClassStatusIcon.tsx
  src/components/ClassTable/ClassStatusSwitch.tsx
  src/components/ClassTable/ClassTable.tsx
  src/components/ClassTable/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useClassStatus.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/class/[classId]/index.ts
  src/pages/api/class/all.ts
  src/pages/api/user/[userId]/class/[action]/[classId].ts
  src/pages/api/user/[userId]/class/[action]/all.ts
  src/pages/class/index.tsx
  think-big.code-workspace
  types/next-auth.d.ts
  types/next.d.ts
  types/userDataModel.d.ts
Labels: new-feature, automerge

#105 fix(build): :bug: tweaks for vercel deploy
  .npmrc
  envcheck.js
  package.json
  pnpm-lock.yaml
  prisma/fakeGen/class.ts
  src/components/ClassTable/ClassAccordianTable.tsx
  src/pages/api/auth/[...nextauth].ts
  types/next-auth.d.ts
Labels: bugfix, ci

#107 fix(app): implement auth paths, fix deployment issues
  next.config.js
  prisma/schema.prisma
  src/components/CenterLoader.tsx
  src/components/SideNav.tsx
  src/components/index.ts
  src/data/index.ts
  src/data/nav.ts
  src/hooks/useClassStatus.ts
  src/hooks/useClasses.ts
  src/layouts/MainLayout.tsx
  src/lib/axiosClient.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/assignment/index.tsx
  src/pages/calendar/index.tsx
  src/pages/class/index.tsx
  src/pages/dashboard/index.tsx
  types/customComponents.d.ts
  types/next-auth.d.ts
  types/next.d.ts
Labels: bugfix

#112 fix(app): :bug: fix types & error handling for deploy test
  src/components/ClassTable/ClassStatusSwitch.tsx
  src/components/GlobalModals/NewUserProgress.tsx
  src/components/UserMenu.tsx
  src/hooks/useClassStatus.ts
  src/hooks/useClasses.ts
  src/hooks/useUser.ts
  src/layouts/MainLayout.tsx
  src/lib/db/class.ts
  src/lib/db/user.ts
  src/lib/httpResponse.ts
  src/lib/prisma.ts
  src/pages/api/class/[classId]/index.ts
  src/pages/api/class/all.ts
  src/pages/api/user/[userId]/class/[action]/[classId].ts
  src/pages/api/user/[userId]/class/[action]/all.ts
  src/pages/api/user/[userId]/class/[action]/index.ts
  src/pages/api/user/[userId]/index.ts
  src/pages/class/index.tsx
  src/pages/index.tsx
  types/global.d.ts
Labels: bugfix

#118 Landing Page (NEEDS LAYOUT FIX)
  public/clement-helardot-95YRwf6CNw8-unsplash.jpg
  public/coding-924920_1920.jpg
  public/landingPage-class-materials.svg
  public/landingpage-stay-organized.svg
  public/landingpage-stay-up-to-date.svg
  public/landingpage-work-together.svg
  src/pages/index.tsx
Labels: new-feature, automerge

#122 fix(ui): 🐛 nav bar active link
  src/components/SideNav.tsx
Labels: bugfix, automerge

#124 chore(build): 🔨 add hook rebase logic
  .github/CODEOWNERS
  .github/renovate.json
  .husky/commit-msg
  .husky/pre-rebase
  .husky/prepare-commit-msg
Labels: enhancement, ci, maintenance

#126 fix(build): :bug: vercel deployment fixes
  .github/renovate.json
  src/pages/api/auth/[...nextauth].ts
  src/pages/dashboard/profile.tsx
Labels: bugfix, automerge

#131 fix(api): :bug: do not block if discord API guild profile 404
  src/lib/externalAPI/discord.ts
  src/pages/api/auth/[...nextauth].ts
Labels: bugfix, automerge

#134 fix(db): :bug: field Validation
  src/pages/dashboard/profile.tsx
Labels: bugfix, automerge

#137 refactor(ui): ♻️ display class list as nested accordion
  .eslintrc.json
  .github/ISSUE_TEMPLATE/04_BUILD_ITEM.md
  src/components/ClassTable/ClassAccordianTable.tsx
  src/components/ClassTable/ClassDetail.tsx
  src/layouts/MainLayout.tsx
  src/pages/class/index.tsx
Labels: refactor
