Repository 100Devs-ADHD/think-big, pull requests merged in 2022-07, with the labels that each got.

#43 Dev to main
  package.json
  pnpm-lock.yaml
Labels: maintenance, automerge

#44 test(app): ✅ added cypress
  cypress.config.ts
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  package.json
  pnpm-lock.yaml
Labels: new-feature, dependencies, automerge

#45 test(app): ✅ added cypress
  cypress.config.ts
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  package.json
  pnpm-lock.yaml
Labels: new-feature, automerge

#46 revert(ui): :rewind: remove storybook
  .storybook/main.js
  .storybook/preview.js
  package.json
  pnpm-lock.yaml
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: maintenance, automerge

#49 chore(deps): bump!
  package.json
  pnpm-lock.yaml
Labels: security, maintenance, automerge

#59 refactor(ci): :recycle: add script output
  .husky/post-merge
Labels: ci

#68 style(ui): 💄 update palette
  .github/deadpendency.yaml
  src/components/HeaderBar.tsx
  src/components/SideNav.tsx
  src/components/UserMenu.tsx
  src/style/baseTheme.ts
  types/mantine.d.ts
Labels: maintenance, automerge

#70 Set up Prisma data schema
  .env.example
  .gitignore
  package.json
  pnpm-lock.yaml
  prisma/dev.db
  prisma/schema.prisma
  src/pages/_app.tsx
  think-big.code-workspace
Labels: enhancement, dependencies, automerge

#72 feat: Next-Auth initial setup
  .env.example
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/components/UserMenu.tsx
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/auth/newuser.tsx
  types/next-auth.d.ts
  types/next.d.ts
Labels: priority-high, new-feature, security, automerge

#92 feat: Class table page starter
  mockdata/nav.ts
  prisma/schema.prisma
  src/components/HeaderBar.tsx
  src/components/SideNav.tsx
  src/hooks/index.ts
  src/hooks/useClasses.ts
  src/lib/axiosClient.ts
  src/lib/index.ts
  src/lib/prisma.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/class/all.ts
  src/pages/class/index.tsx
  src/pages/index.tsx
Labels: new-feature, automerge

#94 feat(ui): ✨ create TagGroup component
  prisma/fakeGen/class.ts
  prisma/seed-data/tags.ts
  src/components/TagGroup.tsx
  src/components/index.ts
  src/pages/class/index.tsx
Labels: new-feature, automerge

#91 feat(ui): user sign up modal
  src/pages/auth/newuser.tsx
Labels: new-feature, automerge

#96 feat(ui): ✨ Class Detail Modal
  prisma/schema.prisma
  src/components/ClassDetail.tsx
  src/components/TagGroup.tsx
  src/components/index.ts
  src/hooks/useClasses.ts
  src/pages/_app.tsx
  src/pages/class/index.tsx
  types/classDetail.d.ts
Labels: new-feature, automerge
